# Generated by Django 4.2.2 on 2023-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket', models.CharField(max_length=100)),
                ('maas', models.CharField(max_length=50)),
                ('seher', models.CharField(max_length=50)),
                ('mezmun', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('basliq', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('staj', models.CharField(max_length=50)),
                ('yash', models.CharField(max_length=50)),
                ('tehsil', models.CharField(max_length=50)),
                ('rejm', models.CharField(max_length=50)),
                ('muqavile', models.CharField(max_length=50)),
            ],
        ),
    ]
