# Generated by Django 4.2.2 on 2023-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_elan_muqavile_alter_elan_rejm_alter_elan_staj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='apply_link',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
