# Generated by Django 4.2.2 on 2023-06-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_elan_apply_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elan',
            name='apply_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
