# Generated by Django 4.2.2 on 2023-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_text_elan_text1_elan_text2_elan_text3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='text_1',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elan',
            name='text_2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elan',
            name='text_3',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elan',
            name='text_4',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elan',
            name='text_5',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
