# Generated by Django 4.2.2 on 2023-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_elan_text_1_elan_text_2_elan_text_3_elan_text_4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket', models.CharField(max_length=100)),
                ('maas', models.CharField(max_length=50)),
                ('seher', models.CharField(max_length=50)),
                ('mezmun', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('basliq', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('text1', models.TextField(max_length=500, null=True)),
                ('text2', models.TextField(max_length=500, null=True)),
                ('text3', models.TextField(max_length=500, null=True)),
                ('text4', models.TextField(max_length=500, null=True)),
                ('text5', models.TextField(max_length=500, null=True)),
                ('text_1', models.TextField(max_length=500, null=True)),
                ('text_2', models.TextField(max_length=500, null=True)),
                ('text_3', models.TextField(max_length=500, null=True)),
                ('text_4', models.TextField(max_length=500, null=True)),
                ('text_5', models.TextField(max_length=500, null=True)),
                ('staj', models.CharField(max_length=100)),
                ('yash', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('rejm', models.TextField(max_length=250)),
                ('muqavile', models.CharField(max_length=100)),
                ('apply_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
