# Generated by Django 4.2.2 on 2023-06-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_neqliyyat_satish_security_senaye_tibb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketinq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket', models.CharField(max_length=100)),
                ('maas', models.CharField(max_length=50)),
                ('seher', models.CharField(max_length=50)),
                ('mezmun', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('basliq', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('text1', models.TextField(max_length=500, null=True)),
                ('text2', models.TextField(max_length=500, null=True)),
                ('text3', models.TextField(max_length=500, null=True)),
                ('text4', models.TextField(max_length=500, null=True)),
                ('text5', models.TextField(max_length=500, null=True)),
                ('text_1', models.TextField(max_length=500, null=True)),
                ('text_2', models.TextField(max_length=500, null=True)),
                ('text_3', models.TextField(max_length=500, null=True)),
                ('text_4', models.TextField(max_length=500, null=True)),
                ('text_5', models.TextField(max_length=500, null=True)),
                ('staj', models.CharField(max_length=100)),
                ('yash', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('rejm', models.TextField(max_length=250)),
                ('muqavile', models.CharField(max_length=100)),
                ('apply_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Techizat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket', models.CharField(max_length=100)),
                ('maas', models.CharField(max_length=50)),
                ('seher', models.CharField(max_length=50)),
                ('mezmun', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('basliq', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('text1', models.TextField(max_length=500, null=True)),
                ('text2', models.TextField(max_length=500, null=True)),
                ('text3', models.TextField(max_length=500, null=True)),
                ('text4', models.TextField(max_length=500, null=True)),
                ('text5', models.TextField(max_length=500, null=True)),
                ('text_1', models.TextField(max_length=500, null=True)),
                ('text_2', models.TextField(max_length=500, null=True)),
                ('text_3', models.TextField(max_length=500, null=True)),
                ('text_4', models.TextField(max_length=500, null=True)),
                ('text_5', models.TextField(max_length=500, null=True)),
                ('staj', models.CharField(max_length=100)),
                ('yash', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('rejm', models.TextField(max_length=250)),
                ('muqavile', models.CharField(max_length=100)),
                ('apply_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
