# Generated by Django 4.2.2 on 2023-08-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_marketinq_techizat'),
    ]

    operations = [
        migrations.AddField(
            model_name='it',
            name='text6',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='it',
            name='text7',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='it',
            name='text_6',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='it',
            name='text_7',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
